#!/bin/sh

BPATH=`dirname $0`
if test -s $BPATH/commons.sh; then
    . "$BPATH/commons.sh"
    test -s "$BPATH/../profile" && . "$BPATH/../profile"
else
    echo "[ERROR] can't find commons.sh" >&2
    exit 1
fi

test -z "$FILTER" && FILTER=".*"
TMPFILE=/tmp/`basename $0`.$$
oc get templates --all-namespaces | grep -v ^NAMESPACE |
    while read project template restofline
    do
	if ! echo "$project/$template" | grep -E "$FILTER" >/dev/null; then
	    continue
	fi
	test -d "$project" || mkdir -p "$project"
	for retry in 1 2 3
	do
	    fetch_template "$project" "$template" >"$TMPFILE" 2>/dev/null
	    if test -s "$TMPFILE"; then
		mv "$TMPFILE" "$project/$template.yml"
		break
	    elif test "$retry" = 3; then
		echo "[WARNING] empty object returned exporting $project/$template" >&2
		rm -f "$TMPFILE"
	    else
		if test "$DEBUG"; then
		    echo "[DEBUG] failed fetching $project/$template ($retry/3)"
		fi
		sleep 3
	    fi
	done
    done

exit $?
